In [1]:
import pandas as pd
import os
import json

In [14]:
jason = pd.read_csv("./data/jdf.csv")
new_df1 = pd.read_csv("./data/new_df1.csv")
new_df2 = pd.read_csv("./data/new_df2.csv")

In [18]:
jason = jason.reset_index().drop(["index", "Unnamed: 0"], axis=1)

In [19]:
new_df1.keys()

Index(['Unnamed: 0', 'beer_name', 'key', 'Style', 'Style Key', 'Brewery',
       'Description', 'ABV', 'Ave Rating', 'Min IBU', 'Max IBU', 'Astringency',
       'Body', 'Alcohol', 'Bitter', 'Sweet', 'Sour', 'Salty', 'Fruits',
       'Hoppy', 'Spices', 'Malty'],
      dtype='object')

In [46]:
# Remove beers that don't intersect for all 3 datasets
names = set(new_df1.beer_name) & set(new_df2.beer_name) & set(jason.name)
jason = jason[jason.name.isin(names)]

In [49]:
jason[jason.hex_color.notna()]

,id,name,nameDisplay,description,abv,styleId,isOrganic,isRetired,labels,status,...,availableId,available,foodPairings,servingTemperature,servingTemperatureDisplay,originalGravity,year,beerVariationId,beerVariation,hex_color
6,JPiPQI,Temptation,Temptation,Blonde Ale aged in used Chardonnay barrels fro...,7.5,132.0,N,N,{'icon': 'https://brewerydb-images.s3.amazonaw...,verified,...,4.0,"{'id': 4, 'name': 'Seasonal', 'description': '...",NaN,NaN,NaN,1.062,NaN,NaN,NaN,FFD878
7,x6bRxw,Ten FIDY,Ten FIDY,"Ten FIDY Imperial Stout â€“ This titanic, immens...",10.5,43.0,N,N,{'icon': 'https://brewerydb-images.s3.amazonaw...,verified,...,1.0,"{'id': 1, 'name': 'Year Round', 'description':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,36080A
13,zS4jh8,Michelob Golden Draft Light,Michelob Golden Draft Light,"Michelob Golden Draft Light, popular in the Mi...",4.1,95.0,N,N,{'icon': 'https://brewerydb-images.s3.amazonaw...,verified,...,1.0,"{'id': 1, 'name': 'Year Round', 'description':...",NaN,cold,Cold - (4-7C/39-45F),NaN,NaN,NaN,NaN,FFD878
14,P8CiOe,Michelob Honey Lager,Michelob Honey Lager,We brew our Michelob Honey Lager with European...,4.9,97.0,N,N,{'icon': 'https://brewerydb-images.s3.amazonaw...,verified,...,1.0,"{'id': 1, 'name': 'Year Round', 'description':...","Turkey Panini, Smoked Thuringer, & Honey-Roast...",cold,Cold - (4-7C/39-45F),1.057,NaN,NaN,NaN,D77200
15,AUl65m,Michelob Light,Michelob Light,"Michelob Light is a full-flavored, rich-tastin...",4.1,94.0,N,N,{'icon': 'https://brewerydb-images.s3.amazonaw...,verified,...,1.0,"{'id': 1, 'name': 'Year Round', 'description':...",NaN,cold,Cold - (4-7C/39-45F),NaN,NaN,NaN,NaN,FFBF42
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2257,93XbpS,Chocolate Stout,Chocolate Stout,Ebony in color with a rich creamy head. The me...,5.8,44.0,N,N,{'icon': 'https://brewerydb-images.s3.amazonaw...,verified,...,1.0,"{'id': 1, 'name': 'Year Round', 'description':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,000000
2283,0AvNCe,Grolsch Premium Lager,Grolsch Premium Lager,NaN,5.0,92.0,N,N,{'icon': 'https://brewerydb-images.s3.amazonaw...,verified,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FBB123
2291,daA1zi,Buster Nut Brown Ale,Buster Nut Brown Ale,We combined a high school murder-movie sense o...,5.4,12.0,N,N,{'icon': 'https://brewerydb-images.s3.amazonaw...,verified,...,1.0,"{'id': 1, 'name': 'Year Round', 'description':...","Great with cured meats, barbecue, red meat, ga...",NaN,NaN,NaN,NaN,NaN,NaN,470606
2292,TpiDMC,Brown Shugga',Brown Shugga',How Come you Taste So Good?? Boatloads of Pure...,9.9,29.0,N,N,{'icon': 'https://brewerydb-images.s3.amazonaw...,verified,...,4.0,"{'id': 4, 'name': 'Seasonal', 'description': '...",NaN,cool,Cool - (8-12C/45-54F),1.100,NaN,NaN,NaN,7B1A00
2297,XybhPj,Plain Porter,Plain Porter,"A jewel in our crown. Officially ""The Best St...",4.2,23.0,N,N,{'icon': 'https://brewerydb-images.s3.amazonaw...,verified,...,1.0,"{'id': 1, 'name': 'Year Round', 'description':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,3F0708

In [102]:
data_we_want = ['name', 'description', 'brewery', 'origin', 'rating', 'ABV', 'IBU','astringency', 'body', 'alcohol', 'bitter', 'sweet', 'sour', 'salty', 'fruits', 'hoppy', 'spices', 'malty']
new_df = jason[['name', 'description', 'abv', 'labels', 'hex_color']]

In [69]:
new_df1.keys()

Index(['Unnamed: 0', 'beer_name', 'key', 'Style', 'Style Key', 'Brewery',
       'Description', 'ABV', 'Ave Rating', 'Min IBU', 'Max IBU', 'Astringency',
       'Body', 'Alcohol', 'Bitter', 'Sweet', 'Sour', 'Salty', 'Fruits',
       'Hoppy', 'Spices', 'Malty'],
      dtype='object')

In [103]:
new_df.name

0       Young's Winter Warmer
1       Young's Winter Warmer
2                 Holzar-Bier
3         Sinebrychoff Porter
4                      Singel
                ...
2293        Bruegel Amber Ale
2294               Brugse Zot
2295        Brugse Zot Dubbel
2296                    Brune
2297             Plain Porter
Name: name, Length: 2298, dtype: object

In [104]:
new_df1[['beer_name','Brewery']]

                         beer_name                                  Brewery
0                            Amber                      Alaskan Brewing Co.
1                       Double Bag                   Long Trail Brewing Co.
2                   Long Trail Ale                   Long Trail Brewing Co.
3     Sleigh'r Dark DoÃ¼ble Alt Ale                  Ninkasi Brewing Company
4                           Sticke           Uerige ObergÃ¤rige Hausbrauerei
...                            ...                                      ...
2671         Young's Winter Warmer                            Eagle Brewery
2672               Winter Shredder                       Cisco Brewers Inc.
2673                    Winter Ale                  Fremont Brewing Company
2674           Red Nose Winter Ale         Natty Greene's Pub & Brewing Co.
2675          Fish Tale Winterfish  Fish Brewing Company / Fishbowl Brewpub

[2676 rows x 2 columns]

In [83]:
type(new_df)

pandas.core.frame.DataFrame

In [91]:
new_df1[new_df1['beer_name'] == 'Young\'s Winter Warmer']

,Unnamed: 0,beer_name,key,Style,Style Key,Brewery,Description,ABV,Ave Rating,Min IBU,...,Body,Alcohol,Bitter,Sweet,Sour,Salty,Fruits,Hoppy,Spices,Malty
2671,5548,Young's Winter Warmer,691,Winter Warmer,17,Eagle Brewery,Notes:,5.0,3.55,35,...,67,17,28,73,19,0,19,32,43,100

In [94]:
new_df2.keys()

Index(['Unnamed: 0', 'brewery_id', 'brewery_name', 'review_time',
       'review_overall', 'review_aroma', 'review_appearance',
       'review_profilename', 'beer_style', 'review_palate', 'review_taste',
       'beer_name', 'beer_abv', 'beer_beerid'],
      dtype='object')

In [105]:
# Merge it all together
new_df = new_df.join(new_df1[['beer_name','Brewery', 'ABV', 'Min IBU', 'Max IBU', 'Astringency',
       'Body', 'Alcohol', 'Bitter', 'Sweet', 'Sour', 'Salty', 'Fruits',
       'Hoppy', 'Spices', 'Malty']].set_index('beer_name'), on='name')
new_df = new_df.join(new_df2[['beer_name', 'beer_style']].set_index('beer_name'), on='name')

In [109]:
new_df.drop_duplicates().to_csv('./data/final_data.csv')

In [2]:
import pandas as pd
final = pd.read_csv("./data/final_data.csv")

In [3]:
final.keys()

Index(['Unnamed: 0', 'name', 'description', 'abv', 'hex_color', 'Brewery',
       'ABV', 'Min IBU', 'Max IBU', 'Astringency', 'Body', 'Alcohol', 'Bitter',
       'Sweet', 'Sour', 'Salty', 'Fruits', 'Hoppy', 'Spices', 'Malty',
       'beer_style'],
      dtype='object')

In [5]:
final.Alcohol.head()

0    17
1    17
2     6
3     8
4    16
Name: Alcohol, dtype: int64

In [7]:
final.drop(['Unnamed: 0', 'labels'], axis=1, inplace=True)

In [8]:
final.to_csv('data/final_data.csv')